repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
      # Sort imports (https://www.directedignorance.com/blog/ruff-sorting-imports-with-pre-commit)
    - id: ruff-check
      args: [ "--select", "I", "--fix"]
    # Run the formatter.
    - id: ruff-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-illegal-windows-names
    -   id: check-json
        exclude: \.vscode/.+\.json
    -   id: check-merge-conflict
    -   id: detect-private-key

